
#INSTALLATION OF THE OPERATING SYSTEM
FROM openjdk:17-jdk

LABEL authors="azeem11"

#PLACEMENT OF THE EXECUTABLE [MICROSERVICE] ON THE IMAGE
COPY target/reservationService-0.0.1-SNAPSHOT.jar app.jar

#EXPOSE PORTS FOR INCOMING TRAFFIC - HOST_PORT:CONTAINER_PORT
EXPOSE 8080:8080

#ENTRYPOINT OF THE CONTAINER THROUGH THE MICROSERVICE
ENTRYPOINT ["java","-jar","app.jar"]